name: New Deploy
on:  
  workflow_dispatch:
jobs:
  deploy-cypress-run:
    runs-on: ubuntu-latest
    name: E2E
    steps:

      - uses: actions/checkout@v2
      - name: Run E2E
        uses: cypress-io/github-action@v2
        #continue-on-error: true
        with:
          start: npm start
          wait-on: 'http://localhost:8888'
      - name: Process artifacts if FAILURE
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots
     

      # Test run video was always captured, so this action uses "always()" condition
      - name: Process artifacts ALWAYS
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos
      - name: Download build artifacts
        if: always()
        uses: actions/download-artifact@v2
        with:
          path: build-artifacts

      - name: Configure AWS credentials
        if: always()
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Backup build artifacts
        if: always()
        run: |
          workflow=$(echo ${{ github.workflow }} | sed -e 's/\W/-/g' -e 's/\(.*\)/\L\1/')
          aws s3 sync build-artifacts s3://fb-artifacts/${{ github.event.repository.name }}/$workflow/${{ github.run_number }}


  send-slack:
    name: Send notification to Slack
    if: always()
    needs: deploy-cypress-run
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notify
      uses: rtCamp/action-slack-notify@v2.1.2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: TIS-SelfService-E2E-Reports 
        SLACK_CHANNEL: general
        SLACK_ICON_EMOJI: ":test_tube:"
        SLACK_TITLE: " " 
        SLACK_MESSAGE: Cypress reports available at https://fb-artifacts/${{ github.event.repository.name }}/${{env.WORKFLOW}}/${{ github.run_number }}/cypress-reports
        SLACK_COLOR: FF00EF
        SLACK_FOOTER: Its impossible to be unhappy when wearing a poncho. 
        MSG_MINIMAL: true

