name: Deploy
on:  
  workflow_dispatch:
jobs:
  deploy-cypress-run:
    runs-on: ubuntu-latest
    name: E2E
    steps:

      - uses: actions/checkout@v2
      - name: Run E2E
        uses: cypress-io/github-action@v2
        #continue-on-error: true
        with:
          start: npm start
          wait-on: 'http://localhost:8888'
      - name: Process artifacts if FAILURE
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Send failure Slack message
        uses: rtCamp/action-slack-notify@v2.1.2
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: TIS-SelfService-E2E-Reports 
          SLACK_CHANNEL: general
          SLACK_ICON_EMOJI: ":test_tube:"
          SLACK_TITLE: "E2E TESTS FAILED" 
          SLACK_MESSAGE: Cypress reports available at https://fb-artifacts/${{ github.event.repository.name }}/${{env.WORKFLOW}}/${{ github.run_number }}/cypress-reports
          SLACK_COLOR: FF0000
          SLACK_FOOTER: Its impossible to be unhappy when wearing a poncho. 
          MSG_MINIMAL: true

      - name: Send failure Slack message
        uses: rtCamp/action-slack-notify@v2.1.2
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: TIS-SelfService-E2E-Reports 
          SLACK_CHANNEL: general
          SLACK_ICON_EMOJI: ":test_tube:"
          SLACK_TITLE: "E2E TESTS PASSED. YAY!!!" 
          SLACK_MESSAGE: Cypress reports available at https://fb-artifacts/${{ github.event.repository.name }}/${{env.WORKFLOW}}/${{ github.run_number }}/cypress-reports
          SLACK_COLOR: 00CC00
          SLACK_FOOTER: Its impossible to be unhappy when wearing a poncho. 
          MSG_MINIMAL: true

      # Test run video was always captured, so this action uses "always()" condition
      - name: Process artifacts ALWAYS
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        if: always()
        with:
          path: build-artifacts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        if: always()
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
  
      - name: Backup build artifacts
        if: always()
        run: |
          workflow=$(echo ${{ github.workflow }} | sed -e 's/\W/-/g' -e 's/\(.*\)/\L\1/')
          aws s3 sync build-artifacts s3://fb-artifacts/${{ github.event.repository.name }}/$workflow/${{ github.run_number }}


  backup-artifacts:
    name: Backup build artifacts
    needs: deploy-cypress-run
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          path: build-artifacts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Backup build artifacts
        run: |
          workflow=$(echo ${{ github.workflow }} | sed -e 's/\W/-/g' -e 's/\(.*\)/\L\1/')
          aws s3 sync build-artifacts s3://fb-artifacts/${{ github.event.repository.name }}/$workflow/${{ github.run_number }}
  send-slack:
        name: Send notification to Slack
        needs: backup-artifacts
        runs-on: ubuntu-latest
        steps:
        - name: Slack Notify
          uses: rtCamp/action-slack-notify@v2.1.2
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_USERNAME: TIS-SelfService-E2E-Reports 
            SLACK_CHANNEL: general
            SLACK_ICON_EMOJI: ":test_tube:"
            SLACK_TITLE: " " 
            SLACK_MESSAGE: Cypress reports available at https://fb-artifacts/${{ github.event.repository.name }}/${{env.WORKFLOW}}/${{ github.run_number }}/cypress-reports
            SLACK_COLOR: FF00EF
            SLACK_FOOTER: Its impossible to be unhappy when wearing a poncho. 
            MSG_MINIMAL: true