name: Create Cypress report

on:
    workflow_dispatch:

jobs:
    cypress-e2e-chrome:
        name: Run on Chrome
        runs-on: ubuntu-latest
        container: cypress/browsers:latest
        env:
          folder_path: ${{ github.run_number }} 

        steps:
            - uses: actions/checkout@v2
           
            - name: Cypress run
              uses: cypress-io/github-action@v2
              continue-on-error: true
              with:
                start: npm start
                browser: chrome  
                wait-on: 'http://localhost:8888'

            - name: Merge test results into one
              run: npm run report:merge

            - name: Generate HTML report
              run: npm run report:generate
          
            - name: Create report artifact
              uses: actions/upload-artifact@v2
              with:
                name: cypress-reports
                path: cypress/reports
            
            - name: Create screenshot artifact   
              uses: actions/upload-artifact@v2
              # No screenshots generated if tests pass.
              if: failure()
              with:
                name: cypress-screenshots
                path: cypress/screenshots

            - name: Create video artifact
              uses: actions/upload-artifact@v2
              # Test run video was always captured, so this action uses "always()" condition
              if: always()
              with:
                name: cypress-videos
                path: cypress/videos
                
            - name: Slack Notify
              uses: rtCamp/action-slack-notify@v2.1.2
              env:
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                SLACK_USERNAME: TIS-SelfService-E2E-Reports 
                SLACK_CHANNEL: general
                SLACK_ICON_EMOJI: ":test_tube:"
                SLACK_TITLE: "" 
                SLACK_MESSAGE: Cypress reports available at https://ficklebobby.github.io/cypress-example-todomvc/${{ env.folder_path }}
                SLACK_COLOR: FF00EF
                SLACK_FOOTER: Its impossible to be unhappy when wearing a poncho. 
                MSG_MINIMAL: true


